# Generated by Django 5.0.4 on 2024-04-19 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=1000)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
                ('fsk', models.IntegerField(choices=[(0, '0'), (6, '6'), (12, '12'), (16, '16'), (18, '18')], default=0)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnails')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('duration_time', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
