# Generated by Django 5.0.4 on 2024-04-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_video_file_video_video_file_alter_video_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='fsk',
            field=models.IntegerField(choices=[(0, '0'), (6, '6'), (12, '12'), (16, '16'), (18, '18')], default=0),
        ),
    ]
