# Generated by Django 5.0.4 on 2024-04-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_description_video_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='release_year',
            field=models.IntegerField(blank=True, default=0, max_length=4, null=True),
        ),
    ]
