# Generated by Django 5.0.4 on 2024-04-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='release_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
