# Generated by Django 5.0.4 on 2024-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_remove_video_img_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
