# Generated by Django 5.0.4 on 2024-04-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_alter_video_duration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('Film', 'Film'), ('Show', 'Show')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(blank=True, choices=[('Thriller', 'Thriller'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Comedy', 'Comedy'), ('Adventure', 'Adventure'), ('Drama', 'Drama'), ('Western', 'Western'), ('Science fiction', 'Science fiction'), ('Documentary', 'Documentary'), ('Crime', 'Crime'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Satire', 'Satire'), ('Horror', 'Horror'), ('Sport', 'Sport')], default='', max_length=100, null=True),
        ),
    ]
